services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    working_dir: /app
    user: "${UID}:${GID}"
    command: sh -c "npm install && npm run dev"
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/mydatabase?schema=public"
      UID: ${UID}
      GID: ${GID}
    depends_on:
      - db
    volumes:
      - ./backend:/app:z

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      UID: ${UID}
      GID: ${GID}
    volumes:
      - ./frontend:/app:z

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: