name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part: [backend, frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ${{ matrix.part }}
        run: npm ci

      - name: Run linter
        working-directory: ${{ matrix.part }}
        run: npm run lint --if-present

      - name: Run tests
        working-directory: ${{ matrix.part }}
        run: npm test
